version: '3'

services:
  drf-db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/vitor
    ports:
      - "5000:5000"
    depends_on:
      - db