# Generated by Django 2.2.3 on 2019-07-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ordem', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordem')),
                ('cor', models.PositiveSmallIntegerField(verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['ordem'],
            },
        ),
    ]
